name: Conway Bikes Order Check

on:
  # Allow manual trigger for testing
  workflow_dispatch:

  # Allow webhook triggering from cron-jobs service
  repository_dispatch:
    types: [cron-trigger]

# Set timezone to Madrid for consistent execution
env:
  TZ: Europe/Madrid

jobs:
  cron-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create environment file
        run: |
          cat > .env << EOF
          # Holded API Configuration
          HOLDED_API_KEY=${{ secrets.HOLDED_API_KEY }}
          HOLDED_BASE_URL=${{ secrets.HOLDED_BASE_URL }}

          # Email Configuration
          SMTP_SERVER=${{ secrets.SMTP_SERVER }}
          SMTP_PORT=${{ secrets.SMTP_PORT }}
          EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
          EMAIL_FROM=${{ secrets.EMAIL_FROM }}

          # Notification Configuration
          TARGET_EMAIL=${{ secrets.TARGET_EMAIL }}

          # Timezone Configuration
          TIMEZONE=${{ secrets.TIMEZONE }}

          # Application Configuration
          CSV_FILE_PATH=Información_EAN_Conway_2025.xlsx - Stammdaten Conway.csv
          LOG_LEVEL=INFO
          LOG_FILE=logs/holded_automation.log

          # Operation Hours Configuration
          OPERATION_START_HOUR=${{ secrets.OPERATION_START_HOUR }}
          OPERATION_END_HOUR=${{ secrets.OPERATION_END_HOUR }}

          # Production Configuration
          TEST_MODE=false
          TEST_EMAIL_ONLY=false
          EOF

      - name: Create logs directory
        run: mkdir -p logs

      - name: Run order check
        run: |
          echo "🚴 Starting Conway Bikes order check..."
          echo "Current time (Madrid): $(TZ=Europe/Madrid date)"
          echo "Note: Checking last 24 hours with duplicate prevention"
          echo "=================================="
          python main.py check
          echo "=================================="
          echo "✅ Order check completed"
        env:
          TZ: Europe/Madrid

      - name: Upload logs as artifact (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: automation-logs-${{ github.run_id }}
          path: logs/
          retention-days: 7

      - name: Upload logs as artifact (weekly)
        if: github.event_name == 'repository_dispatch' && github.event.action == 'cron-trigger'
        uses: actions/upload-artifact@v4
        with:
          name: weekly-logs-${{ github.run_id }}
          path: logs/
          retention-days: 30
        # Upload logs when triggered via cron-jobs webhook
        # This is a simplified approach; adjust as needed
